### ISSUE TITLE
Comments: the very first reply to the very first comment always fail and content is lost

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3152] opened 2021-01-17 04:20 UTC
It looks like it's related to delayed froala initialization, with tinymce it works fine.

https://user-images.githubusercontent.com/3324866/104830904-70e1ef00-58d7-11eb-927c-14d2780f4e5b.mov

**Comment by AntonLV** [comment] 2021-07-28 04:53
I cannot reproduce the problem neither on my DEV version nor on CI.UNA.IO. 
May be it was already fixed with some other issue.

**Closed as completed** 2021-07-28 11:48 UTC
Labels: Bug
