### ISSUE TITLE
'View profile' ACL actions isn't properly working.

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#943] opened 2017-10-24 16:32 UTC
https://una.io/page/view-album-media?id=97&context=album
https://una.io/cmts.php?sys=bx_forum&id=505&cmt_id=1571

**Comment by AntonLV** [comment] 2017-11-02 12:10
I cannot reproduce the issue. Looks like it was fixed in Ticket #906.

**Closed as completed** 2017-12-05 10:12 UTC
Labels: Bug
