### ISSUE TITLE
Notification: fine tuning

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2392] opened 2019-09-20 08:50 UTC
https://una.io/page/view-discussion?id=2982
https://una.io/cmts.php?sys=bx_forum&id=2982&cmt_id=15778

- [x] 1. check if there are proper links for different notification
- [ ] 2. make avatars to be links to profiles in email notification and in onsite notifications
- [x] 3. from Andrew: someone posted a discussion with “friends only” privacy, I replied/commented. All my followers got notification, but can’t open the page (private for them). So, it seems like we should check for Original content privacy when sending our comments notifications

**Comment by AntonLV** [comment] 2020-01-06 14:30
Point №1 was fixed for Befriend and Follow actions. Mention is OK. The other actions should have standard links to Content the action was performed with.

**Comment by AntonLV** [comment] 2020-01-06 14:31
Point №3 cannot be reproduced. Looks like it was fixed in Ticket #2525

**Comment by AntonLV** [comment] 2020-01-07 09:25
Point №2 won't be applied because it's a step back in usability, especially on mobile devices.

**Closed as completed by AntonLV** 2020-01-07 09:25 UTC
